spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://gomesduartedev:FxeHoxaeEExysFIzo3I601a5MoGuuwl3@dpg-cmk1diud3nmc73cn695g-a/api_crud_postgresql
    username: api_crud_postgresql
    password: FxeHoxaeEExysFIzo3I601a5MoGuuwl3
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
spring-doc:
  pathsToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true